spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
#spring.data.mongodb.username=root
#spring.data.mongodb.password=secret
spring.data.mongodb.database=admin
spring.data.mongodb.auto-index-creation=true
#spring.data.mongodb.uri=mongodb://root:secret@localhost:27017/admin
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration 
spring.jpa.hibernate.ddl-auto = update
spring.data.mongodb.uuid-representation=standard